# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 966d98bcd5192cd41d3e402e081e1cc5b7378339af031dcdbee3dad174944331cfd90b1a80fa8a513a6c7f5908f5e2944e9247256ea6aeec81b57b90fd34dd9b

test:
  secret_key_base: 98787adad5d6e818708a88ec612debaab4f369eeaa63ff0f575446727fe131dd468a7c00083f377dbebcd1ad5b3151500f94074844d0364c647ca325388c43c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
